### ISSUE TITLE
why geom doesn't work

### ISSUE THREAD

**Issue by zijane** [r-classes/ds4dh-hw1-zijane#1]
I don't know, what's wrong with my code. Why does R show such mistake: Error in FUN(X[[i]], ...) : object 'green' not found ?
`iris %>%
  ggplot(aes(Sepal.Length, Sepal.Width)) +
  geom_point(aes(color = green))`

**Comment by agricolamz** [comment]
There are two mistakes here:

1. You use color name without quotation marks. Since there is no quotation marks R thinks that you are looking for a variable with name "green":

```
iris %>% 
  ggplot(aes(Sepal.Length, Sepal.Width)) + 
  geom_point(aes(color = "green"))
```

But this code will return red dots.

2. Since information about color comes NOT from the dataframe, you shouldn't use `aes()` function:
```
iris %>% 
  ggplot(aes(Sepal.Length, Sepal.Width)) + 
  geom_point(color = "green")
```
